### ISSUE TITLE
Examples on https://jsonxt.io are dead links

### ISSUE THREAD

**Issue by CluEleSsUK** [Consensas/jsonxt#1]
I hope this is the correct place for this!  
On the https://jsonxt.io/ homepage, when I scroll down to the section on examples (CCCC4 Vaccination Credential,  Mattr/W3C Vaccination Credential) both the originals and the templates are deadlinks.  I tried to figure out the correct URLs, but couldn't be fully sure

EDIT: actually it seems all of the links are broken

**Comment by dpjanes** [comment]
Interesting - thanks. I will try to find out wtf is happening here.

**Comment by dpjanes** [comment]
Fixed, I hope! The issue was we rearranged the code into folders for "python" and "javascript", so we moved the "data" into a common folder (instead of being in the javascript test folder)
